// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctutpzdbezebunzlfnaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dXRwemRiZXplYnVuemxmbmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTczOTYsImV4cCI6MjA2MDMzMzM5Nn0.l_RgixTq6o5zN6OjorWMvWqzqF7XoZGeMbg6kF73es8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);